name: plexos-coad
dependencies:
  - python
  - h5py
  - numpy
  - pandas
  - cython
#  - pymongo
#  - mongodb
  - nose
#  - pip:
#    - "--editable=git+https://github.nrel.gov/hsorense/plexos-coad.git#egg=coad"
